---
title: 積極保全民主的政策 – 前論
author: Tōo Him-tshuan
date: '2020-04-15'
weight: 5
hidden: true
slug: tsik-ki-k-hû-tshî-bîn-tsú-ê-tsìng-tshik-tsiân-lūn
categories:
  - Tsik-ki̍k hû-tshî bîn-tsú --ê tsìng-tshik
tags:
  - 經濟
  - 政治
  - 民粹主義
---

大部分的台灣選舉觀察者攏認為2020年的總統選舉結局表示台灣人真正關心閣想欲保全怹這馬有的自由佮民主， 甚至予蔡英文總統贏韓國瑜的票數破記錄。 隨然選舉了後感覺安心的人足濟， 但是超過五百五十萬的人伨韓國瑜, 國民黨這擺的[後選人](https://www.bloomberg.com/graphics/2020-taiwan-election-results/)。 而且彼些予人伨韓國瑜的因素猶未無去。 若是咱想欲予台灣的民主化變較強， 咱所有關心台灣民主的人一定愛了解三个問題：

1.	世界各民主的國家攏有右派民粹黨支持率雄雄破記錄的形狀到底是對佗位來？
2.	台灣人是安怎避免這的右派民粹主義的浪潮？
3.	了解民粹主義的因素了後，有佗一款的政策會使保全台灣的民主？

# 本係列結構
本係列的目的是利用政治佮經濟學的文獻閣有我家己予各種的資料分拆去來一个仔一个回答頂懸的問題。 我全部的資料佮code攏是保存到我的GitHub內底。

- [第一篇： 民粹主義浪潮是怎樣來到台灣](/台語版/漢字版/積極保全民主的政策/民粹主義浪潮是怎樣來到台灣/)
- 第二篇： 台灣人是怎麼予近年的民粹主義浪潮避免去
- 第三篇： 有佗一款的政策會使避免未來的民粹主義攻擊 

# 本係列的三个重點

## 1. 我欲討論的是右派民粹主義
雖然民粹主義的學家認為民粹主義著是一種政治概念佮政策，左派佮右派攏會使用，但是左派佮右派的民粹政客差別足濟。 上大的差別著是怹推薦的政策佮怹對民主的意見。 就按呢左派 （比如希臘的Syriza黨，西班牙的Podemos黨）佮右派（比如波蘭的Law and Order黨，意大利的Five Star黨，匈牙利的KDNP黨）攏有會當叫民粹黨的政黨。 但是對壢史來講，民主較會受右派民粹黨的傷害，就按呢我主要想欲了解右派的民粹主義。我討論的時陣若是講著民粹政客抑是民粹主義攏是咧講右派的。

## 2. 我欲專門討論經濟佮媒體形狀的影響
因為政治變化佮右派民粹主義的來源足濟，我佇這的佮民粹主義有關係的係列會專門討論經濟佮媒體形壯的影響。我想欲另工閣來討論別的因素，因為政黨認同， 國家認同, 等等因素的變化嘛會影響著民粹主義的支持率。

## 3. 怎樣欲來定義台灣政治的右派
台灣政治上重要的問題著是台灣佮中國的關係，甚至予其他的政治問題定定攏根據這个主要相諍來定義的（比如對國際貿易佮外來投資的意見）。就按呢，咧討論台灣政治的時陣， 左派佮右派是較罕得用的分類。 顛倒反，台灣的政治範圍大部分的人攏是講青色的（伨台灣獨立的民進黨）佮籃色的（唚中的國民黨），各細黨是看怹對這兩个上大政黨有偌肖像佮有偌肯團結予各細黨分到青營佮籃營去。 猶毋過，這个特色毋是講左派佮右派攏無意思的。 確實，青營真像歐洲佮美國的左摒政黨，比論對勞工權利，人權，佮環境政策的對重（論真台灣綠黨嘛是青營內中的政黨）。籃營真像歐洲佮美國的右摒政黨，比論怹對商業友好的政策佮守舊的社會關念。 就按呢，若是有一个政客對商業友好（閣較是對中國來的投資），有守舊概念，閣是唚中, 伊著是所為的台灣右派民粹政客。



