---
title: 'Analysis Replication File - Proactive Policies for Safeguarding Democracy in Taiwan'
author: "Travis Dorsey"
date: "3/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
# Set path for saving local copies of the plots
knitr::opts_knit$set(base.dir = "/Users/sharedcomputer/MMT in Taiwan/Blog Photos")

## Load required libraries
library(readr)
library(janitor)
library(tidyverse)
library(scales)
library(lubridate)
library(tsbox)
library(knitr)
library(kableExtra)
library(directlabels)

```

# Analysis File for Proactive Policies for Safeguarding Democracy in Taiwan
This is a companion file to the series of posts on Proactive Policies for Safeguarding Democracy in Taiwan. All of the original analyses and data wrangling are performed here and should be easy to replicate.

## Part 1: How the Populist Wave Came to Taiwan

```{r tw_gini_fig}
## Download necessary datasets from my github
inequality_url <- "https://raw.githubusercontent.com/dorseytf/TaiwanMMT/master/Taiwan%20Income%20Inequality%20Data.csv"

tw_gini_df <- read_csv(url(inequality_url))[, c(1,2,8,9)] %>%
  gather("inequality_measure", "value", -c(Year, Metric)) %>%
  filter(!is.na(value)) %>%
  clean_names() %>%
  mutate(inequality_measure = str_wrap(inequality_measure, 40))

tw_gini_df %>%
  ggplot(aes(x = year, y = value, color = inequality_measure)) +
  geom_line() +
  facet_wrap(~inequality_measure, scales = "free") +
  scale_color_viridis_d() +
  guides(color = "none") +
  labs(title = "Measures of Income Inequality in Taiwan",
       x = " ",
       y = "Inequality Measure Value")
ggsave("/Users/sharedcomputer/MMT in Taiwan/Blog Photos/Measures of Income Inequality for Taiwan.jpg")
```

```{r tw_savings_fig}
tw_inequality_df <- read_csv(url(inequality_url))[, -c(8:9)] %>%
  gather("quintile", "value", -c(Year, Metric))

tw_inequality_df %>%
  filter(!str_detect(Metric, "Percent distribution")) %>%
  ggplot(aes(x = Year, y = value, color = quintile)) +
  geom_line() +
  geom_dl(aes(label = quintile), method = list("last.points", cex = 0.8)) +
  scale_color_viridis_d(guide = "none") +
  scale_y_continuous(labels = dollar) +
  scale_x_continuous(expand = expand_scale(mult = c(0,0.14))) +
  labs(title = "Average Savings per Household by Income Quintile in Taiwan",
       x = " ",
       y = "Average Savings per Household in NT$")
ggsave("Blog Photos/Average Savings per Household in Taiwan.jpg")
```


```{r tw_earnings_fig}
earnings_urlfile <- "https://raw.githubusercontent.com/dorseytf/TaiwanMMT/master/Taiwan%20Earnings%20Data.csv"

tw_earnings_data <- read_csv(url(earnings_urlfile)) %>%
  clean_names() %>%
  filter(!is.na(metric)) %>%
  separate(year_and_month, c("year", "month")) %>%
  mutate(day = ifelse(month == "FEB", "28", "30")) %>%
  mutate(date = paste(year, month, day, sep = "-")) %>%
  mutate(date = ymd(date)) %>%
  select(-c(year, month, day))

earnings_ts <- ts(tw_earnings_data$statistical_value[which(tw_earnings_data$metric == "Monthly Real Earnings(NT)")],
                  frequency = 12,
                  start = c(1980, 1))

earnings_trend <- decompose(earnings_ts)$trend

ts_df(earnings_trend) %>%
  filter(!is.na(value)) %>%
  ggplot(aes(x = time, y = value)) +
  geom_line() +
  scale_y_continuous(labels = dollar) +
  labs(title = "Real Monthly Earnings in Taiwan",
       subtitle = "Seasonally Adjusted; Industry and Service Sectors",
       caption = "Data source: Directorate-General of Budget, Accounting and Statistics",
       x = " ",
       y = "Real Monthly Earnings (in NT$)")
ggsave("Blog Photos/Real Monthly Earnings in Taiwan.jpg")
```


```{r tw_hmm}
tw_housing_url <- "https://raw.githubusercontent.com/dorseytf/TaiwanMMT/master/Taiwan%20Housing%20Data.csv"

tw_housing_data <- read_csv(url(tw_housing_url)) %>%
  clean_names() %>%
  separate(year_and_quarter, c("year", "qtr"), sep = "Q") %>%
  mutate(year = as.numeric(year) + 1911,
         qtr = as.numeric(qtr)) %>%
  mutate(time = paste0(year, ":Q", qtr)) %>%
  mutate(time = lubridate::yq(time)) %>%
  select(-c(year, qtr)) %>%
  gather("locality", "value", -c(metric, time)) %>%
  mutate(locality = gsub("_", " ", locality)) %>%
  mutate(locality = str_to_title(locality))

tw_housing_data %>%
  filter(metric == "Housing Median Multiple") %>%
  ggplot(aes(x = time, y = value, color = locality)) +
  geom_line() +
  scale_color_viridis_d(name = "Locality") +
  labs(title = "Quarterly Housing Median Multiple for Taiwan and Taipei City",
       x = " ",
       y = "Housing Median Multiple")
ggsave("Blog Photos/Quarterly Housing Median Multiple for Taiwan.jpg")
```


```{r tw_housing_ratio}
tw_housing_data %>%
  filter(!metric %in% c("Housing Median Multiple")) %>%
  ggplot(aes(x = time, y = value, color = locality)) + 
  geom_line() +
  facet_wrap(~metric, scales = "free") +
  scale_color_viridis_d(name = "Locality") +
  labs(title = "Taiwan's Price-to-Income and Loan Payment-to-Income Ratios",
       x = " ",
       y = "Ratio")
ggsave("Blog Photos/Taiwan Housing Ratios.jpg")
```

