baseurl = "https://poli-econ-tw.netlify.app/"
title = "Exploring Taiwan's Political Economy"
subtitle = "Empirical Discussions of Various Interesting Topics"
copyright = "&copy; {year} Travis Dorsey"
theme = "hugo-lithium"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
pluralizeListTitles = false
math = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true

[permalinks]
    zh = "/zh/:year/:slug/"
    tw = "/tw/:year/:slug/"
    en = "/English/:year/:slug/"

[[menu.main]] 
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/English/"
    weight = 2
[[menu.main]]
    name = "中文版"
    url = "/中文版/"
    weight = 3
[[menu.main]]
    name = "台語版"
    url = "/台語版/"
    weight = 4
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/dorseytf/TW_Pol_Econ_Blog"
    weight = 5

[params]
    site = "Exploring Taiwan's Political Economy"
    subtitle = "Empirical Discussions of Various Interesting Topics"
    name = "Travis Dorsey"
    description = "An Exploration of Taiwan's Political Economy"
    
    footer = "&copy; 2020 Travis Dorsey"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "newlogo.jpg"

    [params.logo]
    url = "newlogo.jpg"
    width = 100
    height = 100
    alt = "Logo"
    
[taxonomies]
  tag = "tags"
  categories = "categories"