baseurl = "https://github.com/dorseytf/TW_Pol_Econ_Blog/"
title = "Exploring Taiwan's Political Economy"
copyright = "&copy; {year} Travis Dorsey"
theme = "hugo-lithium"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[permalinks]
    zh = "/zh/:year/:slug/"
    tw = "/tw/:year/:slug/"
    en = "/en/:year/:slug/"

[[menu.main]] 
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Posts"
    url = "/en/"
    weight = 2
[[menu.main]]
    name = "中文版"
    url = "/zh/"
    weight = 3
[[menu.main]]
    name = "台語版"
    url = "/tw/"
    weight = 4
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/dorseytf/TW_Pol_Econ_Blog"
    weight = 5
    
[[menu.en]] 
    name = "About"
    url = "/about/"
    weight = 1
[[menu.en]]
    name = "Posts"
    url = "/en/"
    weight = 2
[[menu.en]]
    name = "中文版"
    url = "/zh/"
    weight = 3
[[menu.en]]
    name = "台語版"
    url = "/tw/"
    weight = 4
[[menu.en]]
    name = "GitHub"
    url = "https://github.com/dorseytf/TW_Pol_Econ_Blog"
    weight = 5

[[menu.zh]] 
    name = "About"
    url = "/about_zh/"
    weight = 1
[[menu.zh]]
    name = "Posts"
    url = "/en/"
    weight = 2
[[menu.zh]]
    name = "中文版"
    url = "/zh/"
    weight = 3
[[menu.zh]]
    name = "台語版"
    url = "/tw/"
    weight = 4
[[menu.zh]]
    name = "GitHub"
    url = "https://github.com/dorseytf/TW_Pol_Econ_Blog"
    weight = 5
    
[[menu.tw]] 
    name = "About"
    url = "/about_tw/"
    weight = 1
[[menu.tw]]
    name = "Posts"
    url = "/en/"
    weight = 2
[[menu.tw]]
    name = "中文版"
    url = "/zh/"
    weight = 3
[[menu.tw]]
    name = "台語版"
    url = "/tw/"
    weight = 4
[[menu.tw]]
    name = "GitHub"
    url = "https://github.com/dorseytf/TW_Pol_Econ_Blog"
    weight = 5

[params]
    name = "Travis Dorsey"
    description = "An Exploration of Taiwan's Political Economy"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "newlogo.jpg"

    [params.logo]
    url = "newlogo.jpg"
    width = 50
    height = 50
    alt = "Logo"