---
title: Proactive Policies for Safeguarding Democracy - Introduction
author: Travis Dorsey
date: '2020-03-30'
weight: 5
slug: proactive-policies-for-safeguarding-democracy-introduction
bibliography: part1_bib.bib
categories:
  - Proactive Policies for Safeguarding Democracy
tags:
  - populism
  - economics
  - politics
---

Most observers of Taiwan’s 2020 general election agree that the results show voters care greatly about protecting their hard-won democracy, with the incumbent Tsai Ying-wen defeating her populist, pro-Beijing opponent with the greatest number of votes for any presidential candidate in Taiwanese history. While many now feel able to breathe a sigh of relief, the fact is that over 5.5 million people (in a total population of 23 million) [voted for the populist candidate](https://www.bloomberg.com/graphics/2020-taiwan-election-results/),^[@bloomber_tw_election] and the political schisms and structural causes for this support remain. For those of us interested in seeing Taiwan’s democracy thrive rather than go on the defensive at every election, we are left pondering several challenging questions:

1.	Why are right-wing populists finding such strong levels of support in democracies around the world, and how was Taiwan almost swept up in this global trend?
2.	What led Taiwanese voters to oppose this trend at the ballot box? 
3.	Knowing what causes support for right-wing populism, what steps could be taken to proactively protect Taiwan’s democracy moving forward?

# Structure of This Series

Each post in this series will be devoted to one of these questions, building on existing scholarly work as well as presenting new analyses to improve our understanding of these pressing issues. All data and R code for the analyses I performed are available through my GitHub. 

- [Part 1: How the Populist Wave Came to Taiwan](/english/proactive-policies-for-safeguarding-democracy/part-1-how-the-populist-wave-came-to-taiwan/)
- [Part 2: How Taiwanese Voters Pushed Back](/english/proactive-policies-for-safeguarding-democracy/part-2-how-did-taiwanese-voters-push-back/)
- [Part 3: Policies to Strengthen Taiwan's Democracy](/english/proactive-policies-for-safeguarding-democracy/part-3-policies-to-strengthen-taiwan-s-democracy)

# Three important points to keep in mind for this series:

## 1. The Focus is on Right-Wing Populism Specifically
My reasoning for this is that, while scholars of populism are quick to point out that populism is essentially just a political tool that can be used by any party or candidate to gain supporters and open the door to their accompanying political ideology, populists on the left and right differ significantly in their proposed solutions to issues, as well as in their likelihood of conflicting with democratic rules and institutions or adopting authoritarian tendencies. Because of this, even though we often see parties from both the left (such as Syriza in Greece and Podemos in Spain) and the right (Law and Justice in Poland, Five Star in Italy, KDNP in Hungary) described as populist parties, the consequences for democracy are usually direr in the wake of right-wing populist victories. Therefore, throughout this series I will be focused specifically on right-wing populism and will use this term interchangeably with “populism” for the sake of brevity. 

## 2. I am Analyzing the Economic Factors and Media Situations That Feed Right-Wing Populism
While there are numerous causes for shifting politics and the rise of right-wing populism, this series will focus mainly on the economic and media situations which lay the groundwork for populist surges. In future series, I hope to dig into additional causes, such as the role of political identity, more deeply as they are also important factors that need to be tackled. 

## 3. How to Define "Right-Wing" in Taiwanese Politics
Taiwanese politics is unique in that the defining issue is Taiwan's relationship with China, and other issues are often defined in terms of this major cleavage (such as views on trade and cross-border investment). The result is that the labels "left-wing" and "right-wing" are less often used to delineate between politicians and parties in Taiwan than they are in European or US politics. Rather, discussions typically define the spectrum as ranging from Independence to Unification with China.^[@tpsr_left_right] The two largest parties, the <span style="color: green"> Democratic Progressive Party (DPP) </span> and the <span style="color: blue"> Kuomintang (KMT) </span>, both lie closer to the center of this spectrum, favoring to maintain the status quo in the near- to medium-term. However, the two parties differ on their long-term goals (the DPP considers Taiwan to already be an independent country and the KMT desires unification with China) as well as their approach to dealing with China (the KMT prefers closer economic and political ties with China, while the DPP prefers closer ties to the US, Japan, and others to protect Taiwans sovereignty).^[@nachman_hioe_20] Taiwan's various third parties are thus typically considered to fall into either the (DPP-aligned) Pan-Green or (KMT-aligned) Pan-Blue camps based on their similarity to, and willingness to work with, these two largest parties. However, this does not mean that left- and right-wing are meaningless terms in Taiwanese politics. Indeed, the Pan-Green camp has a great deal of overlap with Western left-leaning parties, such as a focus on labor rights, human rights, and environmental policy (the Pan-Green camp actually includes the Green Party), while the Pan-Blue camp has much in common with Western right-leaning parties, such as focusing on pro-business policies and more conservative societal values. A right-wing populist in Taiwan would therefore be someone who is strongly pro-China, claims to support conservative societal values, and promotes largely business-friendly policies, and in the context of Taiwan, specifically businesses from China. 


# References

