---
title: 積極保護民主的政策 – 前論
author: 杜欣川
date: '2020-04-02'
weight: 5
slug: 積極保護民主的政策-intro
hidden: true
categories:
  - 積極保護民主的政策
tags:
  - 經濟
  - 民粹主義
  - 政治
---
 
大部分的台灣選舉關注者都同意2020年的總統選舉結果表示台灣人真的很關心又很想保護現在擁有的自由和民主，甚至讓蔡英文總統贏韓國瑜的票數破紀錄了。隨然很多人覺得總於有可以呼吸的感覺了但是實際上是有超過五百五十萬人投給這次的[民粹主義的候選人](https://www.bloomberg.com/graphics/2020-taiwan-election-results/)，而且讓他能夠找到這麼多支持者的政治分裂和結構的原因還有存在。如果想要讓台灣的民主化變得比較強的話，所有關心台灣民主者只好了解三個問題：

1.  世界各民主國家都為什麼會有右派民粹主義支持率突破紀錄的狀況，而台灣怎麼也差點被掃走了？
2.  台灣人是怎麼避免右派民粹主義浪潮的？
3.  了解民粹主義的來源之後，有哪些政策可以保護台灣的民主？

# 本係列結構
本係列的目的就是利用政經學的文獻還有我自己做出來的各種資料分析來一篇一篇的回答上面的問題。我所有的資料和code會存在我的GitHub。

- [第一篇： 民粹主義浪潮如何來台](/中文版/積極保護民主的政策/第一篇民粹主義浪潮如何來台/)
- 第二篇： 台灣人是怎麼避免近年民粹主義浪潮的
- 第三篇： 哪些政策能夠避免未來的民粹主義攻擊

# 本係列的三個重點

## 1. 我會專門討論右派民粹主義
隨然民粹主義學家認為民粹主義是一種不分左右派的政治概念和策略，但是左派的跟右派的民粹政客差別很大，最大的差別在於他們會推薦的政策和他們對民主主義的看法。因此隨然有很多左派政黨（如希臘的Syriza黨和西班牙的Podemos）跟右派政黨（如波蘭的Law and Order, 義大利的Five Star, 和匈牙利的KDNP）都可以說是民粹黨，但是以歷史來講最會傷害民主的就是右派民粹主義，所以我主要了解的是右派民粹主義。因此當我討論到民粹主義的時候，我主要是在講右派的民粹主義。


## 2. 我會專門討論經濟和媒體狀況的影響
因為政治變化跟右派民粹主義的來源很多，所以這一期的關於民粹主義的文章都會專門討論經濟和媒體狀況的影響。 我打算在別期再專門討論到別的因素，因為政黨認同，國家認同，等因素的變化也會影響到民粹主義的支持率。


## 3. 如何定義台灣政治的右派
台灣政治上的定義問題就是台灣跟中國的關係，甚至讓其他的政治問題通常都根據這一主要分歧來定義的（如對國際貿易以及外來投資的意見）。 因此，在討論台灣的政治時，左派跟右派是比較少用到的分類。 相反，台灣的政治範圍通常定義為從獨立到統一。 <span style="color: green"> 民進黨 </span> 跟 <span style="color: blue"> 國民黨 </span>，台灣最大的兩個政黨，都位於頻譜中間，在短期和中期都想要保持現在的狀況。但是，兩黨的長期目標（民進黨認為中華民國已經是一個獨立的國家，可是國民黨願意與中國統一）和與中國打交道的方式（國民黨更希望與中國建立更緊密的經濟和政治聯繫，可是民進黨更希望與美國，日本，等國家建立更緊密聯繫）大不同。 因此，台灣的各小黨由於與這兩個最大政黨的相似性並願意與之合作而落入綠營和藍營。 不過，這個特色並不代表左派跟右派在台灣政治上是完全沒有意義的。 確實，綠營跟歐美的左傾政黨有很多重疊之處，例如對勞工權，人權，以及環境政策的關注（其實綠黨也是綠營的其中一個黨），而藍營跟歐美的右傾黨有很多重疊之處，例如商業友好的政策和保守的社會觀念。 因此，一個對商業友好（尤其是來自中國的投資）又有保守概念的親中政客就是所謂的台灣右派民粹政客。

