---
title: 積極保全民主的政策 – 前論 Tsik-ki̍k pó-tsuân bîn-tsú --ê tsìng-tshik – Tsiân-lūn
author: Tōo Him-tshuan
date: '2020-04-15'
weight: 5
hidden: true
slug: tsik-ki-k-hû-tshî-bîn-tsú-ê-tsìng-tshik-tsiân-lūn
categories:
  - Tsik-ki̍k hû-tshî bîn-tsú --ê tsìng-tshik
tags:
  - king-tsè
  - tsìng-tī
  - bîn-tshuì tsú-gī
---

Tuā-pōo-hun --ê Tâi-uân suán-kí kuan-tshat-tsiá lóng jīn-uî 2020 nî--ê tsóng-thóng suán-kí kiat-kio̍k piáu-sī Tâi-uân-lâng tsin-tsiànn kuan-sim koh siūnn-beh pó-tsuân in tsit-má ū --ê tsū-iû kah bîn-tsú, sīm-tsì hōo Tshuà Ing-bûn tsóng-thóng iânn Hân Kok-jû --ê phiò-sòo phuà-kì-lo̍k. Sui-liân suán-kí liáu-āu kám-kak an-sim --ê lâng tsiok-tsé, tān-sī tshiau-kuè gōo-pah-gōo-tsa̍p-bān--ê lâng thīn Hân Kok-jû, Kok-bîn-tóng tsit-pái--ê [hāu-suán-jîn](https://www.bloomberg.com/graphics/2020-taiwan-election-results/). Jî-tshiánn hit-kuá hōo lâng thīn Hân Kok-jû --ê in-sòo iáu-bē bô-khì. Ná-sī lán siūnn-beh hōo Tâi-uân--ê bîn-tsú-huà pìnn khah kiông, lán sóo-ū kuan-sim Tâi-uân bîn-tsú --ê lâng it-tīng ài liáu-kái sann-ê būn-tê:

1.	Sè-kài kok bîn-tsú--ê kok-ka lóng ū iū-phài bîn-tshuì-tóng tsi-tshî-lu̍t hiông-hiông phuà-kì-lo̍k --ê hîng-tsōng tàu-té sī tuì tó-uī lâi?
2.	Tâi-uân-lâng sī an-tsuánn pī-bián tsit-ê iū-phài bîn-tshuì-tsú-gī--ê lōng-tiâu?
3.	Liáu-kái bîn-tshuì-tsú-gī--ê in-sòo liáu-āu, ū tó-tsi̍t-khuán--ê tsìng-tshik ē-sái pó-tsuân Tâi-uân--ê bîn-tsú?

# Pún Hē-lia̍t Kiat-koo
Pún hē-lia̍t--ê bo̍k-tik sī lī-iōng tsìng-tī kah king-tsè ha̍k--ê bûn-hiàn koh ū guá ka-kī hōo kok-tsiòng--ê tsu-liāu hun-thiah-khì lâi tsi̍t-ê-á-tsi̍t-ê hê-tap tíng-kuân--ê būn-tê. Guá tsuân-pōo--ê tsu-liāu kah code lóng sī pó-tsûn kàu guá--ê GitHub lāi-té. 

- [Te-it-phinn：Bîn-tshuì tsú-gī lōng-tiâu sī tsuánn-iūnn lâi kàu Tâi-uân](/台語版/Tâi-lô-pán/積極保全民主的政策/民粹主義浪潮是怎樣來到台灣/)
- Te-jī-phinn：Tâi-uân-lâng sī tsuánn-iūnn hōo kīn-nî --ê bîn-tshuì-tsú-gī lōng-tiâu pī-bián khì
- Te-sann-phinn： Ū tó-tsi̍t-khuán--ê tsìng-tshik ē-sái pī-bián bī-lâi--ê bîn-tshuì tsú-gī kong-kik

# Pún Hē-lia̍--ê sann-ê tiōng-tiám

## 1. Guá beh thó-lūn --ê sī iū-phài bîn-tshuì tsú-gī
Sui-jiân bîn-tshuì-tsú-gī --ê ha̍k-ka jīn-uî bîn-tshuì-tsú-gī tio̍h sī tsi̍t-tsióng tsìng-tī khài-liām kah tsìng-tshik, tsó-phài kah iū-phài lóng ē-sái iōng, tān-sī tsó-phài kah iū-phài --ê bîn-tshuì tsìng-kheh tsha-pia̍t tsiok-tsè. Siōng-tuā --ê tsha-pia̍t tio̍h sī in tshui-tsiàn --ê tsìng-tshik kah tuì bîn-tsú --ê ì-kiàn. Tsiū-án-ne tsó-phài (pí-jû Hi-la̍h --ê Syriza tóng kah Se-pan-gê --ê Podemos tóng) kah iū-phài (pí-jû Pho-lân --ê Law and Order, Ì-tāi-lī --ê Five Star, Hiong-gâ-lī --ê KDNP) lóng ū ē-tang kiò bîn-tshuì-tóng --ê tsìng-tóng. Tān-sī tuì li̍k-sú lâi kóng, bîn-tsú khah ē siū iū-phài bîn-tshuì-tóng --ê siong-hāi, tsiū-án-ne guá tsú-iàu siūnn-beh liáu-kái iū-phài --ê bîn-tshuì-tsú-gī. Guá thó-lūn --ê sî-tsūn ná-sī kóng tio̍h bîn-tshuì tsìng-kheh ia̍h-sī bîn-tshuì-tsú-gī lóng sī leh kóng iū-phài --ê. 

## 2. Guá beh tsuan-mn̂g thó-lūn king-tsè kap muî-thé hîng-tsiōng--ê íng-hiáng
In-uî tsìng-tī piàn-huà kah iū-phài bîn-tshuì-tsú-gī --ê lâi-guân tsiok-tsè, guá tī tsit-ê kah bîn-tshuì-tsú-gī ū kuan-hē--ê hē-lia̍t ē tsuan-bûn thó-lūn king-tsè kah muî-thé hîng-tsòng ê íng-hióng. Guá siūnn-beh līng-kang koh lâi thó-lūn pa̍t--ê in-sòo, in-uî tsìng-tóng jīn-tông, kok-ka jīn-tông, tíng tíng in-sòo --ê piàn-huà mā ē íng-hióng--tio̍h bîn-tshuì-tsú-gī --ê tsi-tshî-lu̍t.

## 3. Tsuánn-iūnn beh lâi tīng-gī Tâi-uân tsìng-tī--ê iū-phài
Tâi-uân tsìng-tī lāi-té siōng tiōng-iàu--ê būn-tê tio̍h sī Tâi-uân kap Tiong-kok --ê kuan-hē, sīm-tsì hōo kî-tha --ê tsìng-tī būn-tê tiānn-tiānn lóng kin-kì tsit-ê tsú-iàu sio-tsènn lâi tīng-gī --ê (pí-jû tuì kok-tsè bōo-i̍k kap guā-lâi tâu-tsu --ê ì-kiàn). Tsiū-án-ne, leh thó-lūn Tâi-uân tsìng-tī --ê sî-tsūn, tsó-phài kap iū-phài sī khah hán-tit-iōng --ê hun-luī. Tian-tò-píng, Tâi-uân--ê tsìng-tī huān-uî tuā-pōo-hun --ê lâng lóng sī kóng tshenn-sik--ê (thīn Tâi-uân to̍k-li̍p --ê Bîn-tsìn-tóng) kap nâ-sik--ê (tsim Tiong-kok --ê Kok-bîn-tóng), kok sè-tóng sī khuànn in tuì tsit nn̄g-ê siōng tuā --ê tsìng-tóng ū guā siàu-siōng kap ū guā khíng thuân-kiat hōo kok sè-tóng hun kàu tshenn-îng kap nâ-îng khì. Iáu-m̄-kò, tsit-ê ti̍k-sik m̄ sī kóng tsó-phài kap iū-phài lóng bô ì-sù --ê. Khak-si̍t, tshenn-îng tsin-tshiūnn Au-tsiu kap Bí-kok --ê tsó-piànn tsìng-tóng, pí-lūn tuì lô-kang khuân-lī, jîn-khuân, kap khuân-kìng tsìng-tshik --ê tuì-tāng (lūn-tsin Tâi-uân li̍k-tóng mā sī tshenn-îng lâi-té --ê tsìng-tóng). Nâ-îng tsin-tshiūnn Au-tsiu kap Bí-kok --ê iū-piànn tsìng-tóng, pí-lūn in tuì siong-gia̍p iú-hó --ê tsìng-tshik kap siú-kū --ê siā-huē kuan-liām. Tsiū-án-ne, ná-sī tsi̍t-ê tsìng-kheh tuì siong-gia̍p iú-hó (koh khah sī tuì Tiong-kok lâi--ê tâu-tsu), ū siú-kū khài-liām, koh sī tsim-Tiong, I tio̍h sī sóo-uî --ê Tâi-uân iū-phài bîn-tshuì tsìng-kheh.

